### ISSUE TITLE
Primal iOS crashes when deleting Cryllic Extended-B character

### ISSUE THREAD

**Issue by geeknik** [PrimalHQ/primal-ios-app#105]
## Describe the bug
When attempting to delete a Cryllic Extended-B character, Primal crashes. 

### Steps to reproduce
The character in question is  ꙰ and while the screenshot is from Damus, this does affect Primal too. 

![image](https://github.com/PrimalHQ/primal-web-app/assets/466878/b3c51dae-0038-437e-9da3-3beb2dc6b483)

Once your text is formatted as the screenshot, attempt to backspace over  ꙰ and watch it crash. 

### Expected behavior
No crash when I backspace over  ꙰

### Environment
ios 17.1 dev beta
testflight primal

### Additional context
N/A

**Comment by PavleKreator** [comment]
Not able to reproduce. Are you sure this affects primal as well as damus?

**Comment by geeknik** [comment]
It did at the time I reported it. There should be Testflight logs from my device. 👍🏻
