### ISSUE TITLE
Show error message or some kind of useful info if note fails to send

### ISSUE THREAD

**Issue by ghost** [PrimalHQ/primal-ios-app#112]
## Describe the bug
Occasionally (multiple times a day) I will try to send a note but it fails to send. The UI shows a brief loading state, then nothing happens.

### Steps to reproduce
Unknown - this seems to happen to me a few times a day, perhaps a relay issue?

No clear repro steps unfortunately other than replying to another person’s note.

### Expected behavior
If a note fails to send, show the user some kind of useful feedback in UI so they know what action to take (if any), and perhaps what failed (eg. relay not responding)

### Environment
 - 0.90.3#111 
 
https://github.com/PrimalHQ/primal-ios-app/assets/123519473/e356fc58-33c9-4dcb-becc-db5f16aeb882

**Comment by PavleKreator** [comment]
fixed in 2.0
