### ISSUE TITLE
In user profile show "followed by [from people I follow]"

### ISSUE THREAD

**Issue by urza** [PrimalHQ/primal-ios-app#127]
On Twitter, when you go to someones profile, there is the basic info how many followers etc that person has, but there is also "followed by this accounts that you follow" list of icons. 

For example:
![image](https://github.com/PrimalHQ/primal-ios-app/assets/189804/dc16fb33-0cae-477c-910a-28fbbc02642f)

This is important to quickly assert if this profile is real or imposter. There are already imposters on nostr trying to impersonate famous personalities. This would help identify them more easily.

**Comment by nearlymad** [comment]
This would be very helpful.

**Comment by PavleKreator** [comment]
This is coming up in 2.0.
