### ISSUE TITLE
Primal Missing in iOS Notifications Settings Menu

### ISSUE THREAD

**Issue by amunrarara** [PrimalHQ/primal-ios-app#139]
## Describe the bug
The Primal app doesn't trigger any notifications on my iOS device. Inspecting the iOS > Settings > Notifications menu (on the actual OS settings, not the Primal app settings), there is no entry for Primal at all.

I've assured that Notifications are active in the actual Primal app > Settings > Notifications menu. They're all active.

I've attempted reinstalling the app. This does not fix the issue. 

![iOS-Primal-Notifications](https://github.com/user-attachments/assets/976952ad-60a6-4af8-903c-e71a13ff048f)

### Device Specs
iPhone 12 Pro
iOS 18.1.1

### Steps to reproduce
1. Open iOS system Settings (not Primal app settings)
2. Navigate to "Notifications"
3. Scroll down to the P-letter apps
4. Primal is missing

### Expected behavior
- The Primal app should be represented in the Notifications menu.
- Notifications should be triggered on my phone when Primal actions take place

**Comment by swbratcher** [comment]
iPhone 15 Pro (MTU53LL/A)
Fresh upgrade to iOS 18.1.1
Fresh re-install of Primal v2.0.114
Fresh reboot of device after delete/install of Primal App

Confirming under my above specs that no Primal application settings list item appears in the iOS Settings>Notifications list, as shown above by @amunrarara.

**Comment by PavleKreator** [comment]
The app still doesn't have push notification capability, this is not a bug it's a feature request.

Push notifications will be coming in one of the future updates.

**Comment by amunrarara** [comment]
Ah got it. Thanks for the clarification @PavleKreator

**Comment by PavleKreator** [comment]
@amunrarara the app now supports push notifications

**Comment by amunrarara** [comment]
@PavleKreator great news. I'm not getting them, however. Is there a setting I need to enable at the OS level?

**Comment by PavleKreator** [comment]
Yeah, go into the settings and then notification and you'll see the option to enable them
