### ISSUE TITLE
App crashes while trying to Create a Nostr Account

### ISSUE THREAD

**Issue by MarkoBraticevic** [PrimalHQ/primal-ios-app#72]
### Description
The app is crashing when I create a new Nostr Account. The app allows me to fill in my new Nostr account's information, it then shows me my account preview, but when I click on the last step, "Create Nostr Account", the app crashes. 

### Steps to reproduce
- Click on "Create account" when first loading the app
- Fill in the required fields
- Create Nostr Account

### Expected behavior
The app should create a brand new Nostr Profile with all the given information that the user fills in. There should be no crash.

### Actual Behavior 
When clicking on the "Create Nostr Account" button, the app crashes.

**Comment by mbrat1** [comment]
Fixed in build 0.22.3
